# docker-compose.yml defines services for Redis, the application and optionally RedisInsight
version: '3.8'
services:
  redis:
    image: "redis:7.0"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: "redislabs/redisinsight:latest"
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis

  app:
    image: "golang:1.20"
    container_name: agent-app
    working_dir: /app
    volumes:
      - .:/app
    command: ["go", "run", "./cmd/agentctl", "--config", "configs/default.yaml"]
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
